# Settings for Backend (on Cloud Run).
# See https://firebase.google.com/docs/app-hosting/configure#cloud-run
runConfig:
  # Optional: specify region or serviceId if non-default
  # region: australia-southeast1
  # serviceId: compass7-6c50f-app-hosting
  minInstances: 0
  maxInstances: 100
  concurrency: 80
  cpu: 1
  memoryMiB: 512

# Environment variables and secrets.
# See https://firebase.google.com/docs/app-hosting/configure#user-defined-environment
env:
  # Plain environment variables for build-time & runtime
  - variable: NEXT_PUBLIC_FIREBASE_API_KEY
    value: "AIzaSyADxweaJ_4xg7QFs9lLPuJvqsIqzP-F7MI"
    availability:
      - BUILD
      - RUNTIME
  - variable: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    value: "compass7-6c50f.firebaseapp.com"
    availability:
      - BUILD
      - RUNTIME
  - variable: NEXT_PUBLIC_FIREBASE_PROJECT_ID
    value: "compass7-6c50f"
    availability:
      - BUILD
      - RUNTIME
  - variable: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
    value: "compass7-6c50f.firebasestorage.app"
    availability:
      - BUILD
      - RUNTIME
  - variable: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
    value: "54353024313"
    availability:
      - BUILD
      - RUNTIME
  - variable: NEXT_PUBLIC_FIREBASE_APP_ID
    value: "1:54353024313:web:bc712d0ea63ee3c2eb84e8"
    availability:
      - BUILD
      - RUNTIME
  - variable: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
    value: "G-NSCK1T1BYF"
    availability:
      - BUILD
      - RUNTIME
  - variable: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
    value: "AIzaSyDWYY-cnevIBIUGZHOtHaatJSenWP6f5nk"
    availability:
      - BUILD
      - RUNTIME

  # Secret for Gemini API key — create this in Secret Manager first!
  # See https://firebase.google.com/docs/app-hosting/configure#secret-parameters
  - variable: GEMINI_API_KEY
    secret: gemini-api-key
    availability:
      - RUNTIME
